### ISSUE TITLE
Issue with subsection completion

### ISSUE THREAD

**Issue by sigzegv** [artempyanykh/zeta-note#4]
I'm trying your LSP server in **nvim 0.5**, and I must admit I really like it.
It globally work fine, but there is an issue about completion. I don't really know if it's a server issue or client issue. (but I don't have this issue with other lsp servers, so I'm wondering)

The issue is when I try to complete a subsection, the completion provide the correct list of possible choices, but when I select a choice it only selects mi the "##" part of the title and not the text. If I type the title by hand the reference works fine, but this really reduces the workflow speed.

Take a look at the action :
![zeta-bug](https://user-images.githubusercontent.com/6304596/131876324-9568767c-a2e9-4be3-9dd9-1d5143aea87e.gif)

**Comment by sigzegv** [comment]
Well it seem to be an issue with my autocomplete plugin while I'm able to drop the completion text in the file is I directly use omni completion shortcut <ctrl-x><ctrl-o>

**Comment by artempyanykh** [comment]
Happy to hear you have pin pointed the issue @sigzegv ! Could you share what autocompletion plugin you use with nvim (and what causes an issue) in case someone encounters a similar problem?

**Comment by sigzegv** [comment]
yes  had the issue with [hrsh7th/nvim-compe](https://github.com/hrsh7th/nvim-compe), but with [nvim-lua/completion-nvim](https://github.com/nvim-lua/completion-nvim) or [hrsh7th/nvim-cmp](https://github.com/hrsh7th/nvim-cmp) (this one is a rewrite of nvim-compe) all works fine.
