### ISSUE TITLE
Update `lsp-types` to a newer version

### ISSUE THREAD

**Issue by rbozan** [artempyanykh/zeta-note#5]
Thanks for the crate.

https://github.com/artempyanykh/zeta-note/blob/main/lsp-document/Cargo.toml#L12

I'd suggest updating the `lsp-types` to a newer version, also because `tower-lsp` uses a newer version, which makes it 'harder' to use this crate as this crate uses an older version.

https://github.com/ebkalderon/tower-lsp/blob/master/Cargo.toml#L23

**Comment by artempyanykh** [comment]
Thanks for raising this @rbozan. I'll look into it.

**Comment by artempyanykh** [comment]
@rbozan I've published versions of lsp-document built against lsp-types 0.89, 0.90, and 0.91. Hope it helps.

**Comment by rbozan** [comment]
Thank you
